image: java:8-jdk

stages:
  - build
  - publish
  - cleanup

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx512m"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - apt update && apt install -y make
  script:
    - make installDist

deb:build:
  stage: build
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  before_script:
    - export VERSION=$(./version.sh)
    - echo "Building signald version $VERSION"
  script:
    - gbp dch --ignore-branch --debian-tag="%(version)s" --git-author --new-version="$VERSION"
    - cat debian/changelog
    - dpkg-buildpackage -b
    - cp -rv ../signald_${VERSION}* .
  artifacts:
    paths:
      - "signald_*"

deb:publish:
  stage: publish
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  tags:
    - package-signer
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
    - export SUITE=$(get-suite)
    - export VERSION=$(./version.sh)
    - mkdir -p public/dists/${SUITE}/
    - mc cp -r -q "minio/updates.signald.org/dists/${SUITE}/" public/ || true
  script:
    - gpg --detach-sign signald_${VERSION}*.deb
    - cd public
    - release-deb ../ "${SIGNING_KEY}"
    - gpg --export --armor "${SIGNING_KEY}" > apt-signing-key.asc
    - for f in apt-signing-key.asc dists/${SUITE}/main/binary-amd64/signald_${VERSION}* $(find dists/ -type f | grep -v -E "\.deb$"); do mc cp -q "$f" "minio/updates.signald.org/$f"; done
  artifacts:
    paths:
      - "signald_*.sig"
  dependencies:
    - deb:build

deb:cleanup:
  stage: cleanup
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  before_script:
    - mc config host add minio "${MINIO_URL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}"
  script:
    - repo-cron minio/updates.signald.org
