stages:
  - lint
  - build
  - test

clang-format:
  image: debian:latest
  stage: lint
  before_script:
    - apt-get update && apt-get install -y clang-format git python3 wget make
  script:
    - ci/format.sh
  needs: []

build-java-8:
  image: openjdk:8-jdk
  stage: build
  needs: []
  before_script:
    - apt update && apt install -y make
  except:
    - schedules
  script:
    - make installDist
  artifacts:
    paths:
      - build/

build-java-11:
  image: openjdk:11-jdk
  stage: build
  needs: []
  before_script:
    - apt update && apt install -y make
  except:
    - schedules
  script:
    - make installDist
  artifacts:
    paths:
      - build/

deb:build:
  image: registry.git.callpipe.com/finn/debian-repo-builder:latest
  stage: build
  needs: []
  before_script:
    - export VERSION=$(./version.sh)
    - echo "Building signald version $VERSION"
  script:
    - gbp dch --ignore-branch --debian-tag="%(version)s" --git-author --new-version="$VERSION"
    - cat debian/changelog
    - dpkg-buildpackage -b
    - cp -rv ../signald_${VERSION}* .
  except:
    - schedules
  cache:
    key: deb-builder
  artifacts:
    paths:
      - "signald_*"

test:integration:
  image: openjdk:11-jdk
  stage: test
  needs: []
  before_script:
    - cp tools/log4j2.xml src/main/resources/log4j2.xml
  script:
    - ./gradlew integrationTest --info
  variables:
    SIGNAL_URL: https://signal-server.signald.org
  artifacts:
    reports:
      junit: build/test-results/integrationTest/TEST-*.xml